services:
  mongo:
    container_name: notesdb
    restart: always
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - ./notes_db:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d

volumes:
  notes_db:

